gemini-hlsw/lucuma-tmp-api

modules/core/src/main/scala/lucuma/odb/api/model/Editor.scala
modules/core/src/main/scala/lucuma/odb/api/model/TopLevelModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/AsterismMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetMutation.scala

Adds some potential for verification to editing and uses it for default asterism editing.  The asterism is associated with targets, but previously the target references were taken without verifying that they refer to actual targets.  Now a lookup is performed and the edit fails with an error if any targets are not found.

Editing Updates

---

modules/core/src/main/scala/lucuma/odb/api/model/Event.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SubscriptionType.scala

Instead of receiving every edit event, you get events for particular items.

Added edit event filtering on id

---

modules/core/src/main/scala/lucuma/odb/api/repo/ProgramRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SubscriptionType.scala

An update to subscriptions to accept a program id argument such that only events that impact the associated program are received by the client.  For example, only events for the targets referenced by a particular program.

Pid-matching subscriptions

---

modules/service/src/main/scala/lucuma/odb/api/service/Routes.scala
modules/service/src/main/scala/lucuma/odb/api/service/Subscriptions.scala

Sangria places results in a JSON object with a `data` field.  When we add results to a streaming message `DataWrapper` we end up with nested `data` fields.  I'd fixed this for subscription results, but we need this at a higher level to handle one-off queries over a web socket connection.

Pull up data stripping

---

modules/core/src/main/scala/lucuma/odb/api/repo/AsterismRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/AsterismSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ProgramSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/RepoContext.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetSchema.scala

As requested, adds an `observations` field to `Target`.  In this model, an observation has an optional asterism.  If the asterism is defined then it has a `Set` of targets.  So this will return all observations having an asterism that refers to this target.
@rpiaggio  Since targets (and asterisms too for that matter) can be shared across programs, do we want to add an optional program id argument and filter?

target => observations

---

docs/units.md
modules/core/src/main/scala/lucuma/odb/api/schema/TargetSchema.scala

A minor consistency update to use "microarcseconds" everywhere rather than a mix of "microarcseconds" and "microarcsecs".

spell out microarcseconds

---

modules/core/src/main/scala/lucuma/odb/api/schema/SubscriptionType.scala
modules/service/src/main/scala/lucuma/odb/api/service/Connection.scala
modules/service/src/main/scala/lucuma/odb/api/service/OdbService.scala
modules/service/src/main/scala/lucuma/odb/api/service/Routes.scala

This PR introduces connection keep alive messages from the server.  There are a couple of caveats. 
Rather arbitrarily, it uses a 5 second keep alive message interval.  There seems to be no standard agreeing upon the timeout period between client and server and at any rate the underlying web socket ping-pong frames are independent of this setting.  Longer settings like 2 minutes cause the Playground to timeout and stop subscriptions.  It's unclear what value makes sense.
An outstanding issue with the Playground app is that when the user stops a subscription, it dutifully sends a `stop` streaming message but never actually terminates the connection.  If the user starts another subscription it sets up another web socket connection instead of reusing the existing one.  This means that after …

connection keep alive

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/PlannedTimeSummaryModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/GeneralSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ProgramSchema.scala

Adds a placeholder for planned time calculation summaries.  As I understand it, this is being displayed in the UI but we're a long way from being able to calculate it.
If merged, new observations would come with a random planned time summary.  A program would accurately display the sum of planned time for its observations (though once we have OR groups etc. this will have to change).
```
{
"data": {
"program": {
"id": "p-2",
"name": "Observing Stars in Constellation Orion for No Particular Reason",
"plannedTime": {
"pi": {
"minutes": 312
},
"uncharged": {
"minutes": 31
},
"execution": {
"minutes": 343
}
},
"observations": [
{
"id": "o-2",
"plannedTime": {
"pi": {
"minutes": 92
},
"uncharged": {
"minutes": 4
},
"execution": {
"minutes": 96
}
}
},
...
```

Planned time placeholder

---

modules/core/src/main/scala/lucuma/odb/api/model/AsterismModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/InputError.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ProgramModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/AsterismRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/LookupSupport.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ProgramRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

Pending an update to supply the client with an id-pool for use (as discussed), this PR allows ids to be provided by the client.  Duplicates are not yet checked for program ids, but this is needed quickly for work on a demo today so I'm sending it as-is and will fix it up subsequently.

Allow ids to be provided by client during creation

---

modules/core/src/main/scala/lucuma/odb/api/model/AsterismModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/Event.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ProgramModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/AsterismRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ProgramRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SubscriptionType.scala

Collapses created and updated events into one.  Simplifies logic surrounding inserts.  This is a breaking change.

Event refactor

---

modules/core/src/main/scala/lucuma/odb/api/model/Sharing.scala
modules/core/src/main/scala/lucuma/odb/api/repo/AsterismRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/EventService.scala
modules/core/src/main/scala/lucuma/odb/api/repo/LookupSupport.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/OdbRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ProgramRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TableState.scala
modules/core/src/main/scala/lucuma/odb/api/repo/Tables.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/MutationType.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SharingMutation.scala

I'm part-way through refactoring sharing/unsharing, but the change set is already pretty large and I have something that might be usable for the requested feature of target/observation sharing.  There will be a follow-up PR with the remainder of the refactoring which should make the various sharing options more similar.  For now, this will add `shareTargetsWithObservations` and `unshareTargetsWithObservations`.  The long-term fate of this is questionable because it requires working with asterisms, which for the moment must be `Default` asterisms.

Target observation link

---

modules/service/src/main/scala/lucuma/odb/api/service/Connection.scala
modules/service/src/main/scala/lucuma/odb/api/service/Subscriptions.scala
modules/service/src/main/scala/lucuma/odb/api/service/syntax/Json.scala

When there is no `data`, send an `error` message instead of a `data` message with no `data` field.

Update streaming message sent for error

---

modules/core/src/main/scala/lucuma/odb/api/model/AsterismModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/AsterismRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/AsterismMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SharingMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetMutation.scala

A minor update to sharing (though it will break anything other than target/observation sharing).  Makes the asterism/program and target/program sharing API similar to the target/observation (plural on each side of the share) and moves them all into the `SharingMutation`.

More Sharing

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/PlannedTimeSummaryModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ProgramModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala

When using Explore, switching from one target to another generates spurious edits.  For example, if the focus is in the target name when clicking on a different target the focus is lost.  That triggers a `mutation` request from the client whether or not the target name has actually changed.  
```
2020-11-10T13:58:34.800652+00:00 app[web.1]: [ioapp-compute-2] INFO  l.o.a.s.Routes - Received message from client: Text('{
2020-11-10T13:58:34.800668+00:00 app[web.1]: "type" : "start",
2020-11-10T13:58:34.800668+00:00 app[web.1]: "id" : "6761a6a7-2b5b-4855-9b11-c2e93cc9092e",
2020-11-10T13:58:34.800669+00:00 app[web.1]: "payload" : {
2020-11-10T13:58:34.800680+00:00 app[web.1]: "query" : "\n      mutation($input: EditSiderealInput!) {\n        updateSiderealTarget(input: $input) {\n …
```

stop spurious events

---

modules/core/src/main/scala/lucuma/odb/syntax/LoggerOps.scala
modules/core/src/main/scala/lucuma/odb/syntax/package.scala
modules/service/src/main/scala/lucuma/odb/api/service/Connection.scala
modules/service/src/main/scala/lucuma/odb/api/service/OdbService.scala
modules/service/src/main/scala/lucuma/odb/api/service/Routes.scala
modules/service/src/main/scala/lucuma/odb/api/service/Subscriptions.scala
modules/service/src/main/scala/lucuma/odb/api/service/package.scala

A few minor logging updates to avoid flooding the log:
1) Lowers the priority of keep alive messages to debug.
2) Uses `log4cats` everywhere.
3) Redacts authorization information coming in websocket `connection_init` message `payload`.

Less logging

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala

Adds the ability to disconnect observations and asterisms (via `updateObservation`, passing in `null` for `asterismId`).  Switches to clue `Input` in general for observation editing.

Unset asterism, etc. with null value

---

modules/core/src/main/scala/lucuma/odb/api/model/ConfigModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/FiniteDurationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/GmosModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/InputValidator.scala
modules/core/src/main/scala/lucuma/odb/api/model/ManualSequence.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/OffsetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/StepModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/WavelengthModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/syntax/InputValidatorOps.scala
modules/core/src/main/scala/lucuma/odb/api/model/syntax/package.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/test/scala/lucuma/odb/api/model/ConfigModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/FiniteDurationModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/GmosModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/ManualSequenceSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/OffsetModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/StepModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/WavelengthModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbConfigModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbDeclinationModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbFiniteDurationModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbGmosModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbManualSequence.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbOffsetModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbStepModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbWavelengthModel.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

Adds basic GMOS (North and South) static and dynamic configuration (filters, dispersers, etc.) along with a subset of sequence steps.  This has not yet been tied into the GraphQL schema.  There is no editing support (only initial creation).
In most cases you will see (a) simple model class that holds the data and (b) a `Create` class that will be used as a GraphQL input parameter.  The input parameter is similar in structure but holds different values.  For example whereas a wavelength is a single value a wavelength input has options in various units.
* Low-level input types introduced here are: `FiniteDurationModel`, `OffsetModel`, `WavelengthModel`.
* GMOS-specific definition in `GmosModel`
* Sequence definition in: `ConfigModel`, `StepModel`, `ManualSequence`.
* `ObservationModel` …

GMOS Sequence (Part 1)

---

modules/core/src/main/scala/lucuma/odb/api/repo/OdbRepo.scala

Stops using `DebuggingRef`, a custom `Ref` that does some logging and handles modify retries itself.  This was part of a debugging effort for the "spinning dots of death" issue that plagued Explore in the early days.  If the spinning dots don't return then I'll remove `DebuggingRef` altogether.

Back out DebuggingRef

---

modules/service/src/main/scala/lucuma/odb/api/service/Connection.scala
modules/service/src/main/scala/lucuma/odb/api/service/Routes.scala
modules/service/src/main/scala/lucuma/odb/api/service/Subscriptions.scala

This PR purports to handle reinitialization without requiring a new web socket connection.  Fair warning, it will require some testing and may not in fact, um, work.

Handle graph QL protocol-level reinitialization

---

modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/OneToManyUnique.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConstraintSetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/test/scala/lucuma/odb/api/model/OneToManyUniqueSpec.scala

This is a temporary fix to make the constraint set UI work until the `observation`  <-> `pointing` api revamp has been completed (#186). At that point the API for `observation` <-> `constraint` set will  be reworked to match.

Allows for unsetting the constraint set to observation link

---

build.sbt
modules/core/src/main/scala/lucuma/odb/api/model/AsterismModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ConstraintSetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ProgramModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/AsterismMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/AsterismSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConstraintSetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConstraintSetSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/GeneralSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ProgramSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbAsterismModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbConstraintSetModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbObservationModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbProgramModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbTargetModel.scala
modules/core/src/test/scala/lucuma/odb/api/repo/ObservationRepoSpec.scala
modules/core/src/test/scala/lucuma/odb/api/repo/TargetRepoSpec.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

Adds a `NonEmptyStringType` GraphQL scalar and converts the various names to `NonEmptyString` and `Option[NonEmptyString]`.  This moves emptiness checking from the realm of user input checks to schema violations.

Nonempty string scalar

---

modules/core/src/main/scala/lucuma/odb/api/model/GcalModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/PlannedTime.scala
modules/core/src/main/scala/lucuma/odb/api/schema/StepSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbGcalModel.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

GCAL-specific exposure and coadds are actually instrument configuration values and shouldn't be duplicated here.

Remove gcal exposure and coadds

---

modules/core/src/main/scala/lucuma/odb/api/repo/ResultPage.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/Paging.scala
modules/core/src/test/scala/lucuma/odb/api/repo/PagingQuerySpec.scala

A `totalCount` field tells the caller, regardless of the page size, how many total items are forthcoming.  This is useful, for example, to determine whether a constraint set is shared by multiple observations.  You can select the observations associated with the constraint set and ask for its `totalCount`.
For example, to see the total target count for the `targets` query (along with the target names):
```
query Targets {
targets(programId: "p-2", first: 100) {
totalCount
nodes {
name
}
}
}
```
might return (say) 3 targets
```
{
"data": {
"targets": {
"totalCount": 3,
"nodes": [
{
"name": "NGC 5949"
},
{
"name": "NGC 3269"
},
{
"name": "NGC 3312"
}
]
}
}
}
```
Asking for only 2 targets per page would return the two selected targets but the `totalCount` remains `3`:
```
query Targets { …
```

Adds a `totalCount` field to the paging connection

---

modules/core/src/main/scala/lucuma/odb/api/model/Breakpoint.scala
modules/core/src/main/scala/lucuma/odb/api/model/GmosModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/PlannedTime.scala
modules/core/src/main/scala/lucuma/odb/api/model/SequenceModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/StepConfig.scala
modules/core/src/main/scala/lucuma/odb/api/model/StepModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SequenceSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/StepSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/SequenceModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/StepModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbSequenceModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbStepModel.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

A bit of a deck-chair shuffling of the step model on the road to adding ids.  It removes a layer of hierarchy and offers a `Step` interface that contains everything except the instrument-specific bits, making it possible to use most of it w/o knowing the instrument.

Small step refactor

---

modules/core/src/main/scala/lucuma/odb/api/model/AsterismModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/AtomModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ConstraintSetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/Database.scala
modules/core/src/main/scala/lucuma/odb/api/model/InstrumentConfigModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ProgramModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/SequenceModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/StepModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/Store.scala
modules/core/src/main/scala/lucuma/odb/api/model/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ValidatedInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/ids.scala
modules/core/src/main/scala/lucuma/odb/api/repo/AsterismRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ConstraintSetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/Ids.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ProgramRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TableState.scala
modules/core/src/main/scala/lucuma/odb/api/repo/Tables.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SequenceSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/StepSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbAtomModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbStepModel.scala
modules/core/src/test/scala/lucuma/odb/api/repo/arb/ArbTables.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

This PR grew from an attempt to add atom and step ids and lead to a refactoring of the various top-level item `create` methods.  In particular they needed access to some of the lookup/store features that were previously done exclusively in the various repos.  This meant abstracting these features into a `Database` trait that is provided upon creation.

Atom and step ids (Part 1)

---

modules/core/src/main/scala/lucuma/odb/api/model/ConfigurationAlternativesModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/SpatialProfileModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConfigurationAlternativesSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConfigurationQuery.scala
modules/core/src/main/scala/lucuma/odb/api/schema/QueryType.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SpatialProfileSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SpectralDistributionModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SpectralDistributionSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/WavelengthSchema.scala
modules/service/src/main/scala/lucuma/odb/api/service/OdbService.scala

This PR is the first to get basic-case ported into lucuma-tmp-api. It defines a single query endpoint to get a list of confgurations for spectroscopy
This PR only defines the input types and also to get familiar with sangria and graphql, we still need to define the return type and hook it to the algorithm.
Sample of a query:
```
query{
spectroscopy(input: {
wavelength: {
nanometers: 1000
},
simultaneousCoverage: {
nanometers: 610
},
resolution: 2,
signalToNoise: 10,
spatialProfile: {
sourceType: GAUSSIAN_SOURCE,
fwhm: {
arcseconds: 1
}
},
spectralDistribution:BLACK_BODY,
magnitude: {
value: 3.55,
band: J,
system: VEGA
},
redshift: 1.5
})
}	
```

Basic case porting I

---

modules/core/src/main/scala/lucuma/odb/api/repo/AsterismRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ConstraintSetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ExecutionEventRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ProgramRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ResultPage.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ExecutionRecordSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObjectIdSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationQuery.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/Paging.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ProgramQuery.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ProgramSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/RepoContext.scala
modules/core/src/test/scala/lucuma/odb/api/repo/ObservationRepoSpec.scala
modules/core/src/test/scala/lucuma/odb/api/repo/OdbRepoTest.scala

Updates the `observations` query to make `programId` optional and accept an optional `observationIds` list.  Now it works like:
* Only `programId` specified => Retrieve observations associated with the program
* Only `observationIds` specified => Retrieve matching observations (regardless of program)
* Neither specified => Retrieve all observations
* Both specified => Error
Updates `programs` query in a similar way, accepting an optional `programIds` list.  I would update the other top-level items similarly but it is unclear whether sharing with ids will live on.
Changes `first` parameter to be optional, defaulting for now to `Integer.MaxValue`.

update observations query, make `first` parameter optional

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/model/SpectroscopyRequirements.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbObservationModel.scala

This is a minor, mostly content-free PR that simply reorders the `ObservationModel` fields to keep target, constraints, and requirements together and in that order (matching the Observation tab in Explore).  Having just gone through a lengthy conflict resolution, my hope is that this will help simplify future rebases.

Reorder ObservationModel

---

modules/core/src/main/scala/lucuma/odb/api/model/ConstraintSetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConstraintSetSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationGroupSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationQuery.scala

We will be adding grouping of observations by various criteria.  The existing grouping-by-constraint-set code was very specific to constraint sets so I generalized it to make it available for reuse.

generalize grouping

---

modules/core/src/main/scala/lucuma/odb/api/model/ConstraintSetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConstraintSetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceRequirementsMutation.scala

Removes a bit of code duplication but more importantly makes it easier to add new observation bulk edit operations.

generalize bulk edit

---

modules/core/src/main/scala/lucuma/odb/api/schema/ObservationGroupSchema.scala

Swap `ObjectType` for the less constraining `OutputType` to accommodate things like list outputs.

Loosen grouping type

---

build.sbt
modules/core/src/main/scala/lucuma/odb/api/model/AtomModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/GmosModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/NumericUnits.scala
modules/core/src/main/scala/lucuma/odb/api/model/SequenceModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/StepConfig.scala
modules/core/src/main/scala/lucuma/odb/api/model/StepModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SharingMutation.scala

Adds the `warn-macros:after` flag and saves the need for `@nowarn` annotations.

Add warn after flag and remove nowarn annotation

---

modules/core/src/main/scala/lucuma/odb/api/model/ValidatedInput.scala
modules/service/src/test/scala/MutationSuite.scala
modules/service/src/test/scala/OdbSuite.scala

Adds an update to `OdbSuite` to allow testing queries that are expected to fail.  It also introduces some cruft that will be removed when the next clue update is published.

Allow expecting error messages

---

modules/service/src/test/scala/ObservationEditSubscriptionSuite.scala

Switches the target subscription test to an observation subscription test in order to facilitate [pending updates in the target API](https://github.com/gemini-hlsw/lucuma-tmp-api/pull/353).

Switch target subscription to observation subscription

---

modules/core/src/main/scala/lucuma/odb/api/model/ConstraintSetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConstraintSetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConstraintSetSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/ConstraintSetModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbConstraintSetModel.scala
modules/service/src/test/scala/QuerySuite.scala

Removes the constraint set name, adds a `Default` constraint set model that matches the UI and switches the observation model default to use it.

Constraint Set Evolution

---

modules/core/src/main/scala/lucuma/odb/api/repo/ExecutionException.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala

Changes
```
type Observation {
...
targets: TargetEnvironment
...
}
```
to
```
type Observation {
...
targets: TargetEnvironment!
...
}
```

Make observation targets required

---

modules/core/src/main/scala/lucuma/odb/api/schema/TargetSchema.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

It was possible to specify a Magnitude error when creating a Magnitude, but they were not available in queries.

Add error to magnitudes for queries

---

modules/core/src/main/scala/lucuma/odb/api/model/DatabaseReader.scala
modules/core/src/main/scala/lucuma/odb/api/model/DatabaseState.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/BulkReplaceTargetListInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/CommonTargetEnvironment.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/CreateTargetEnvironmentInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/CreateTargetInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/EditTargetAction.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/SelectTargetEnvironmentInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/SelectTargetInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetCreator.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetEditor.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetEnvironmentContext.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetEnvironmentGroup.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetEnvironmentModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/Ids.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TableState.scala
modules/core/src/main/scala/lucuma/odb/api/repo/Tables.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SubscriptionType.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbTargetModel.scala
modules/core/src/test/scala/lucuma/odb/api/repo/arb/ArbTables.scala

The `TargetEnvironment` ID was added to `lucuma-core` after it was initially created here.  This PR just switches to `lucuma-core` to be consistent with all the other ID definitions.

Use lucuma-core TargetEnvironment

---

modules/core/src/main/scala/lucuma/odb/api/model/targetModel/EditSiderealInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetModel.scala

The `lucuma-core` version of `Target.properMotion` was updated and this project can now take advantage of it.

Remove proper motion optic

---

modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

Hacks in a way to set the `SourceProfile` in the sample targets in `Init`.  I don't know whether they correspond to reality but it's good to have something set for those targets.
The source profile information will be added to the GraphQL input and the hack will be removed in a subsequent PR.

Sample profiles

---

modules/core/src/main/scala/lucuma/odb/api/schema/TargetQuery.scala

A discussion with Andy led to an investigation which uncovered that I hadn't hooked up the query that returns _all_ science targets for a program.  I added it to the API queries but renamed to `scienceTargets`.  Gone is `referencedScienceTargets` which was the set of targets referenced by at least one observation.  You can get this via `targetGroup` and didn't seem all that useful anyway.

Removes referencedScienceTargets, adds scienceTargets

---

modules/core/src/main/scala/lucuma/odb/api/schema/SourceProfileSchema.scala

I'm not sure where this falls on the spectrum from dumb to good so I'd like some input.  The idea is to make the source profile query output match the JSON input required to create it.  Eventually this idea would be applied to the entire `Target` type.
So practically speaking this means removing all the GraphQL `union`s that would otherwise be present.  Instead all the possible values turn into fields with `Option` values.  A few tradeoffs occur to me:
* If what you get from a query matches the form and content of what you need to do to create an object, then it makes copy/paste/edit script or playground sessions easier?  
* You don't need to see the input type if you know the output type and vice-versa.
* Less verbose / cumbersome than the `... on Whatever` query syntax
* You can not …

No union source profile

---

modules/core/src/main/scala/lucuma/odb/api/model/ConstraintSetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceConfigurationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/model/SpectroscopyRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/model/syntax/PrismOps.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/EditAsterismInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetEnvironmentModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala

This is an implementation change, but not a change to the input or output GraphQL types.  It uses `StateT` editors across the `ObservationModel` hierarchy for consistency and flexibility.  At the "repo" level there is still a mix of `ValidatedInput[State ...]]` and `StateT` which is a bit awkward, but  I plan to address that.

Use StateT across ObservationModel

---

modules/core/src/main/scala/lucuma/odb/api/model/syntax/LensOps.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/NonsiderealInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/SiderealInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/SourceProfileModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SourceProfileSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetMutation.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbSourceProfileModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbTargetModel.scala

Swaps `CreateSourceProfileInput` for `SourceProfileInput` which will be used for both creating and editing.  Adds a `sourceProfile` field to the target editor.  At the moment, you have to replace the entire source profile if you want to replace any part of it.  That will be addressed in the next PR, when it comes.

Editable source profile (Part 1)

---

modules/core/src/main/scala/lucuma/odb/api/model/EditorInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/syntax/LensOps.scala
modules/core/src/main/scala/lucuma/odb/api/model/syntax/PrismOps.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/SiderealInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/SourceProfileModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SourceProfileSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetQuery.scala
modules/core/src/main/scala/lucuma/odb/api/schema/syntax/InputType.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbSourceProfileModel.scala

Next installment in editable source profiles.  Continues turning the `CreateFooInput`s that work for creation only into `FooInput`s that work for creation or editing.  All the fields becomes optional but on creation required fields are checked and flagged if missing.  On editing you only need to specify the things that are changing.  For example, switching from one type of `SourceProfile` to another (e.g., `Point` to `Gaussian`) requires specifying both the `fwhm` and the spectral definition whereas editing the fwhm of an existing `Gaussian` doesn't require the spectral definition.
I'm working my way down from the top and have `SourceProfileInput`, `GaussianInput`, `SpectralDefinitionInput`, `EmissionLinesInput`, and `BandNormalizedInput` converted so far.

Editable source profile (Part 2)

---

modules/core/src/main/scala/lucuma/odb/api/model/targetModel/SourceProfileModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SourceProfileSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbSourceProfileModel.scala

Makes it possible to edit band brightness values.  You reference the bands you want to edit and then supply just the changes.  
For example, to change the value of the "H" magnitude, you don't need to specify the units (they remain unchanged).  Nor do the unchanged magnitudes of other bands need to be mentioned:
```
"sourceProfile": {
"point": {
"bandNormalized": {
"brightnesses": [
{
"band": "H",
"value": 9.999
}
]
}
}
}
```
To remove just the error value:
```
"sourceProfile": {
"point": {
"bandNormalized": {
"brightnesses": [
{
"band": "H",
"error": null
}
]
}
}
}
```
of course you can do both at once and edit other magnitudes at the same time
```
"sourceProfile": {
"point": {
"bandNormalized": {
"brightnesses": [
{
"band": "H",
"value": 9.999
"error": null
},
{
"band": "K",
"value": …
```

Editable source profile (Part 4)

---

modules/core/src/main/scala/lucuma/odb/api/model/targetModel/SourceProfileModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SourceProfileSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbSourceProfileModel.scala

This installment updates the emission line input to make it editable and uses the editor in its containing emission line*s* input.  This allows adding new emission lines or editing existing ones identifying them by wavelength.  Deletion support, as for bands in band normalized, is pending.

Editable source profile 5

---

modules/core/src/main/scala/lucuma/odb/api/model/targetModel/SourceProfileModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SourceProfileSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbSourceProfileModel.scala
modules/service/src/test/scala/test/targets/SourceProfileSuite.scala

Proposes adding `editBrightnesses` and `deleteBrightnesses` in addition to `brightnesses` in `BandNormalizedInput`.  So you use `brightnesses` to set the magnitudes to a given list of values.  This matches the `brightnesses` field in the output type.  If you want to make changes to existing brightnesses (adding or modifying) you can instead (or in addition) set `editBrightnesses` to the changes you want to make.  Finally `deleteBrightnesses` can be set the bands of the corresponding entries to remove.
Adds the same pattern for wavelengths and emission lines.

Editable source profile 7

---

modules/core/src/main/scala/lucuma/odb/api/model/ConstraintSetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ElevationRangeModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConstraintSetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConstraintSetSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/test/scala/lucuma/odb/api/model/ConstraintSetModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/ElevationRangeModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbConstraintSetModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbElevationRange.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbObservationModel.scala
modules/service/src/test/scala/MutationSuite.scala

Updates the constraint set graph to be consistent with source profile.  Namely:
* Combines the create and edit inputs into a single input that works for either, checking arguments appropriately for each case
* Allows all parts of the tree to be edited independently.  You can update just the `min` airmass range for example.
* Makes the constraint set output shape match the input.  In other words, removes the `Union` in favor of optional `airmassRange` and `hourAngleRange` under `elevationRange`

Constraint set makeover

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/model/SpectroscopyRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceRequirementsMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceRequirementsSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbScienceRequirements.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala
modules/service/src/test/scala/QuerySuite.scala
modules/service/src/test/scala/test/TestInit.scala

Makes `ScienceRequirements` resemble `SourceProfile`, `ConstraintSet`, and `ScienceConfiguration`:
* Combines create and edit inputs
* Renames `scienceRequirements` / `spectroscopyRequirements` to `scienceRequirements` / `spectroscopy`

Convert science requirements

---

modules/core/src/main/scala/lucuma/itc/client/ItcClient.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/OdbCtx.scala
modules/service/src/main/scala/lucuma/odb/api/service/Config.scala
modules/service/src/main/scala/lucuma/odb/api/service/Main.scala
modules/service/src/test/scala/OdbSuite.scala

Updates the ITC client to use a simple forever `Map` cache of results.  I think this is good enough for the throwaway API service, especially since it is restarted daily.  There is a `useCache` argument (`true` by default) that can be used to skip the cache lookup.
Switches to the production ITC because I need to update the client for the updated ITC API.

ITC result cache

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbObservationModel.scala
modules/core/src/test/scala/lucuma/odb/api/repo/ObservationRepoSpec.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala
modules/service/src/test/scala/ObservationEditSubscriptionSuite.scala
modules/service/src/test/scala/OdbSuite.scala
modules/service/src/test/scala/QuerySuite.scala
modules/service/src/test/scala/test/TestInit.scala

Following the discussion in [Shortcut](https://app.shortcut.com/lucuma/story/1209/add-user-supplied-observation-details#activity-1221), this PR renames the currently unused observation `name` field to `subtitle`.
It also adds a generated `title` field to the observation output that matches the value currently shown in Explore.  I don't expect Explore to actually use the `title` field but this makes it available for API users.

Observation subtitle (aka "detail")

---

modules/core/src/main/scala/lucuma/odb/api/schema/StepSchema.scala

On request, this PR removes the `stepType` field from `GmosNorthStep` and `GmosSouthStep`.  It is still available in `stepConfig.stepType`.

Remove extra stepType field

---

modules/core/src/main/scala/lucuma/odb/api/schema/ManualConfigSchema.scala

As @rpiaggio pointed out, you can get the `setupTime` from the `plannedTime` so this is redundant at best.

Remove extra setupTime field

---

modules/core/src/main/scala/lucuma/gen/gmos/GmosNorthSequenceState.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/GmosNorthLongSlit.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/syntax/GmosNorthDisperserOps.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/syntax/GmosSouthGratingOps.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/syntax/package.scala
modules/core/src/main/scala/lucuma/itc/client/ItcSpectroscopyInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/GmosModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceConfigurationModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/GmosSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceConfigurationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceConfigurationSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/GmosModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbGmosModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbScienceConfigurationModel.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala
modules/service/src/test/scala/test/TestInit.scala

Renames GMOS "disperser" to "grating".  Sorry for the hassle but it isn't just capriciousness but rather a suggestion/request from Andy.  There's a matching change to `core` but it can be folded in later.

Rename GMOS grating

---

modules/core/src/main/scala/lucuma/itc/client/ItcSpectroscopyInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceConfigurationModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceConfigurationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceConfigurationSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbScienceConfigurationModel.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

Removes the `slitWidth` field of the long slit modes.  The slit width is determined by the FPU. It isn't clear what we'd do with `slitWidth` and we shouldn't allow it to differ from FPU anyway.  Over in `ScienceRequirements` there is a `focalPlaneAngle` which I believe is used to hold the user's requirement for the slit width.

Remove slitWidth from longslit modes

---

modules/core/src/main/scala/lucuma/gen/gmos/GmosNorthInitialDynamicConfig.scala
modules/core/src/main/scala/lucuma/gen/gmos/GmosSouthInitialDynamicConfig.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/Acquisition.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/GmosLongSlit.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/GmosNorthLongSlit.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/GmosSouthLongSlit.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/Science.scala
modules/core/src/main/scala/lucuma/odb/api/model/GmosModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/longslit/AdvancedConfig.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/syntax/GmosNorthFilterOps.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/syntax/GmosSouthFilterOps.scala
modules/core/src/test/scala/lucuma/gen/gmos/longslit/GmosNorthLongSlitSuite.scala

Applies the values in the `AdvancedConfig`, if any, to produce GMOS long slit sequences.
Wavelength dithers and spatial offsets are now simply looped as long as necessary.  To get the standard repeating ABBA sequence the default wavelength dithers have to be 0, 5, 5, 0 nm for example and the spatial offsets 0, 15, 15, 0 arcsec.

Respect settings in AdvancedConfig when generating the sequence

---

modules/core/src/main/scala/lucuma/odb/api/schema/MutationType.scala
modules/core/src/main/scala/lucuma/odb/api/schema/QueryType.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SubscriptionType.scala

No actual API update, just sorts the order by name so that they appear sorted in the playground.

Sort queries, mutations and subscriptions

---

modules/core/src/main/scala/lucuma/odb/api/model/ExecutionEventModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/StepRecord.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ExecutionEventRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/DatasetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ExecutionEventMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ExecutionEventSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbDatabase.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbExecutionEventModel.scala
modules/core/src/test/scala/lucuma/odb/api/repo/ExecutionEventRepoSpec.scala
modules/service/src/test/scala/test/seqexec/VisitSuite.scala

Refactors the event API, standardizing events for the sequence, step and dataset.  Each event is given a `location` identifying the associated element and a `payload` with actual event data.  This separates the two concerns and follows the recommended practice of nesting objects to facilitate API evolution.
Events are not added or directly used by Explore so hopefully this will not occasion any changes to the UI.  Instead, this is part of the the API intended for use by Observe as it executes an observation.

Event API Standardization

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetMutation.scala
modules/service/src/test/scala/MutationSuite.scala
modules/service/src/test/scala/test/targets/AsterismMutationSuite.scala
modules/service/src/test/scala/test/targets/TargetEnvironmentMutationSuite.scala

Renamed the bulk edit mutations `bulkEdit*` for clarity and to match the corresponding `BulkEdit*Input`s.  Nested the selection into its own `BulkEditSelectInput` object.

Bulk Edit Inputs

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/PlannedTimeSummaryModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ProgramSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbObservationModel.scala

A small, nonbreaking, change to stop storing the planned time summary.  These are supposed to be computed and will change as you edit the observation.  For now we can just generate a stable, if bogus, value.

Don't store planned time summary

---

modules/core/src/main/scala/lucuma/gen/SequenceComputation.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/GmosLongSlit.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/GmosNorthLongSlit.scala
modules/core/src/main/scala/lucuma/gen/gmos/longslit/GmosSouthLongSlit.scala
modules/core/src/main/scala/lucuma/itc/client/ItcClient.scala
modules/core/src/main/scala/lucuma/itc/client/ItcResult.scala
modules/core/src/main/scala/lucuma/odb/api/model/ConfigurationMode.scala
modules/core/src/main/scala/lucuma/odb/api/model/ExposureMode.scala
modules/core/src/main/scala/lucuma/odb/api/model/ExposureTimeMode.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/longslit/AdvancedConfig.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/longslit/AdvancedConfigInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/longslit/GmosLongslitMath.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ExecutionSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/GmosSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ItcSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceModeMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceModeSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TimeSchema.scala
modules/core/src/test/scala/lucuma/gen/gmos/longslit/GmosNorthLongSlitSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbExposureMode.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbScienceMode.scala
modules/service/src/main/scala/lucuma/odb/api/service/Config.scala

Adds `overrideWavelength` and `overrideExposureTimeMode` to the science mode advanced configuration input and output.  They can be set to ignore the science requirements and use a different wavelength and/or exposure time mode.  If set to explicit exposure count and time then the call to ITC is bypassed (for now anyway -- eventually we need to make a call to get the acquisition time).

More advanced gmos long slit configuration

---

modules/core/src/main/scala/lucuma/odb/api/model/DatasetModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/DatasetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/DatasetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ExecutionEventMutation.scala
modules/service/src/test/scala/test/seqexec/VisitSuite.scala

Normalizes the mutations that are intended for Observe and Chronicle.  In particular, the `setDatasetQaState` with its list of arguments turned into `editDataset` with `select` and `patch` inputs like the other edit mutations.
I don't think this one will necessitate any substantive changes to Explore.

Normalize observe mutations

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetMutation.scala
modules/service/src/test/scala/test/GroupIncludeDeletedSuite.scala
modules/service/src/test/scala/test/targets/TargetGroupIncludeDeletedSuite.scala
modules/service/src/test/scala/test/targets/TargetMutationSuite.scala

Updates `deleteObservation`, `deleteTarget`, `undeleteObservation` and `undeleteTarget` to follow the convention of taking a single input object parameter named after the mutation itself (e.g., `DeleteObservationInput`).  All the inputs reuse the same selection input used by the corresponding `edit` method.  For example,
```
{
"deleteObservationInput": {
"select": {
"observationIds": [ "o-2" ]
}
}
}
```
For better or worse, this makes it very easy to delete many observations at once.  For example by selecting the program you could delete _all_ of its observations in a single mutation.  Fortunately this is easy to undo using the same selection input with `undeleteObservation`.

normalize (un)delete

---

modules/core/src/main/scala/lucuma/odb/api/model/ProgramModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ProgramRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ProgramMutation.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbProgramModel.scala
modules/core/src/test/scala/lucuma/odb/api/repo/ObservationRepoSpec.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala
modules/service/src/test/scala/test/TestInit.scala

Switches `updateProgram` to the `edit`/`select`/`patch` pattern followed by observations and targets.
```
mutation EditProgram($editProgramInput: EditProgramInput!) {
editProgram(input: $editProgramInput) {
name
}
}
"editProgramInput": {
"select": {
"programId": "p-2"
},
"patch": {
"name": "Biff"
}
}
```

updateProgram => editProgram

---

modules/core/src/main/scala/lucuma/gen/gmos/longslit/GmosLongSlit.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/longslit/AdvancedConfig.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/longslit/AdvancedConfigInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/longslit/DeltaWavelengthCalculator.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/longslit/GmosLongslitMath.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/longslit/LongSlit.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceModeMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceModeSchema.scala

Switches to decimal wavelength dithers in advanced config, adds `Nm` to the name to clarify the units, and fixes a bug in creating the advanced config input type.

Wavelength dithers decimal nm

---

modules/core/src/main/scala/lucuma/odb/api/schema/ObservationGroupSchema.scala
modules/service/src/test/scala/test/targets/TargetQuerySuite.scala

I made a mistake in naming the return type of the `targets` query and the `targetGroup` query.  They were both `TargetSelectResult` but contained different items. I'm surprised this didn't generate an error since there were two definitions of the same GraphQL type.
I fixed this by making all the grouping query results contain the word "Group".  For example, `targetGroup` now returns a `TargetGroupSelectResult` and `scienceModeGroup` returns a `ScienceModeGroupSelectResult`.
I'm sorry for the inconvenience this causes.  Removing grouping and adding filters was a huge change so unfortunately we may uncover more of these.

Fix targets query result type bug

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ProgramModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/TopLevelUpdateInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetModel.scala
modules/service/src/test/scala/MutationSuite.scala
modules/service/src/test/scala/test/ProgramMutationSuite.scala
modules/service/src/test/scala/test/targets/TargetMutationSuite.scala

When updating programs, observations or targets errors may be reported.  They may occur in one or more items but previously there was no way of knowing which ones generated each issue.  This update will prepend the type (`program`, `observation`, or `target` along with (up to 10 of) the ids of the associated problematic values.  See updated test cases for examples.

Improve mutli-item update error messages

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ProgramModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/TopLevelUpdateInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/WhereObservationInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/WhereProgramInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/WhereTargetInput.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationGroupSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ProgramSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetSchema.scala
modules/core/src/test/scala/lucuma/odb/api/repo/ObservationRepoSpec.scala
modules/service/src/test/scala/test/GroupIncludeDeletedSuite.scala
modules/service/src/test/scala/test/ObservationUndeleteSuite.scala
modules/service/src/test/scala/test/TestInit.scala
modules/service/src/test/scala/test/targets/TargetUndeleteSuite.scala

The PR adjusts the API to
* Move the `existence` property from the `Program`, `Observation`, and `Target` `WHERE` clauses to the update input itself, but expressed as a boolean `includeDeleted` flag.
* Remove the `includeDeleted` flag from simple one-value-by-id `program`, `observation` and `target` queries since presumably if you're searching for a particular id you want it whether or not it is deleted.
* Make `deleteObservation`, `undeleteObservation`, `deleteTarget` and `undeleteTarget` not offer an `includeDeleted` argument because it is now implied  by the nature of the operation itself.
Moving the `existence` flag was done to
* Provide just one way to indicate whether or not to include deleted values throughout the API.  Previously it was via the `includeDeleted` flag in some …

includeDeleted

---

modules/core/src/main/scala/lucuma/odb/api/schema/ProgramSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ProposalSchema.scala

The schema defined both `Partner` and `partner` enums and they were identical. This removes `partner` and moves some proposal stuff over from `ProgramSchema` over to where it belongs in `ProposalSchema`.
The only visible difference should be that `partner` goes away and `PartnerSplitsInput` `partner` field is now type `Partner` instead of `partner`.

Remove duplicate  enum
