.gitignore
Procfile
build.sbt
modules/service/src/main/scala/lucuma/odb/api/service/Main.scala
project/plugins.sbt

Following guidelines from https://devcenter.heroku.com/articles/deploying-scala.
I've already created the pipeline and linked to this GitHub repo. Let's deploy a review app to see if everything works and then we can merge, which will move it to staging.

Deploy to Heroku.

---

modules/core/src/main/scala/lucuma/odb/api/model/AsterismModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/syntax/ValidatedInputOps.scala
modules/core/src/main/scala/lucuma/odb/api/model/syntax/package.scala
modules/core/src/main/scala/lucuma/odb/api/repo/AsterismRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/LookupSupport.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ProgramRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/Tables.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/AsterismMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/AsterismSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetMutation.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

Fixes a bug with asterism creation and adds target and (default) asterism sharing/unsharing with programs.

Target and Asterism Sharing with Programs

---

build.sbt
project/plugins.sbt

Removing a plugin that was leftover from an older caliban experiment.

Remove caliban plugin

---

modules/service/src/main/scala/lucuma/odb/api/service/Subscriptions.scala

Sends events without nesting `data` fields.  For example
```
{
"type" : "data",
"id" : "1",
"payload" : {
"data" : {
"targetEdited" : {
"oldValue" : {
"name" : "Betelgeuse"
},
"newValue" : {
"name" : "Zero"
}
}
}
}
} 
```
instead of
```
{
"type" : "data",
"id" : "1",
"payload" : {
"data" : {
"data" : {
"targetEdited" : {
"oldValue" : {
"name" : "Betelgeuse"
},
"newValue" : {
"name" : "Zero"
}
}
}
}
}
} 
```

Strip nested data

---

modules/core/src/main/scala/lucuma/odb/api/schema/SharingMutation.scala

As requested, adds an observation event when a target is shared with an observation.

fire observation event

---

modules/core/src/main/scala/lucuma/odb/api/model/MagnitudeModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetSchema.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

Adds target magnitude schema.  Also makes program id list optional when creating targets.

Add target magnitude

---

modules/core/src/main/scala/lucuma/odb/api/repo/EventService.scala
modules/core/src/main/scala/lucuma/odb/api/repo/OdbRepo.scala
modules/service/src/main/scala/lucuma/odb/api/service/Connection.scala
modules/service/src/main/scala/lucuma/odb/api/service/Main.scala
modules/service/src/main/scala/lucuma/odb/api/service/Subscriptions.scala

Attempting to track down and issue seen in testing, this adds a bit of logging to subscriptions and responses.

Add a bit of FS2 logging

---

modules/core/src/main/scala/lucuma/odb/api/repo/DebuggingRef.scala
modules/core/src/main/scala/lucuma/odb/api/repo/OdbRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/MutationType.scala
modules/core/src/main/scala/lucuma/odb/api/schema/OdbSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SharingMutation.scala
modules/service/src/main/scala/lucuma/odb/api/service/Main.scala
modules/service/src/main/scala/lucuma/odb/api/service/OdbService.scala

Adds a bit of debugging info in an attempt to collect more information about an issue where mutations hang in the API service, causing "spinning dots of death" in the UI.

debugging dots of death

---

modules/service/src/main/scala/lucuma/odb/api/service/Init.scala
scripts/example.py

Updates `Init` to make it easier to specify the initial targets, adds an example python script that adds additional targets.

Example script

---

modules/core/src/main/scala/lucuma/odb/api/model/AsterismModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/AsterismMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/AsterismSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SharingMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetMutation.scala
modules/core/src/test/scala/lucuma/odb/api/model/AsterismSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbAsterismModel.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

Asterism name in model

---

build.sbt
modules/core/src/main/scala/lucuma/odb/api/model/ConfigModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/FiniteDurationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/GmosModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/OffsetModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/StepModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConfigSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/FiniteDurationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/GeneralSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/GmosSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/InstrumentSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ManualSequenceSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/OdbSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/OffsetSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/StepSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/WavelengthSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/GmosModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbGmosModel.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

Second in a series of GMOS sequence PRs. Adds query schema support for manual sequence, hooks it up to Observation.

GMOS Sequence (Part 2)

---

modules/core/src/main/scala/lucuma/odb/api/schema/ConfigSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/InstrumentSequenceSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/StepSchema.scala

Distinct GraphQL types are required for each instrument / step type combination.

types for each instrument / step kind

---

modules/core/src/main/scala/lucuma/odb/api/model/ManualSequence.scala
modules/core/src/main/scala/lucuma/odb/api/model/SequenceModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/InstrumentSequenceSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SequenceSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/ManualSequenceSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/SequenceModelSuite.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbManualSequence.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbSequenceModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/Helper.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

An update to the sequence model to incorporate scheduling units (atoms) and breakpoints.

Adds breakpoints and atoms

---

modules/core/src/main/scala/lucuma/odb/api/repo/ConstraintSetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/Ids.scala
modules/core/src/main/scala/lucuma/odb/api/repo/LookupSupport.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/OdbRepo.scala
modules/core/src/main/scala/lucuma/odb/api/repo/OneToManyUnique.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TableState.scala
modules/core/src/main/scala/lucuma/odb/api/repo/Tables.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/core/src/test/scala/lucuma/odb/api/model/OneToManyUniqueSpec.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbOneToManyUnique.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/SplitSetHelper.scala
modules/core/src/test/scala/lucuma/odb/api/repo/ConstraintSetRepoSpec.scala
modules/core/src/test/scala/lucuma/odb/api/repo/ObservationRepoSpec.scala
modules/core/src/test/scala/lucuma/odb/api/repo/OdbRepoTest.scala
modules/core/src/test/scala/lucuma/odb/api/repo/arb/ArbTables.scala

This PR is built on top of #148.
Naming is hard. Feel free to suggest different names for some of these things. I won't be offended.

Create ConstraintSetRepo and associated changes/tests.

---

modules/core/src/main/scala/lucuma/odb/api/repo/TopLevelRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/AsterismMutation.scala
modules/core/src/test/scala/lucuma/odb/api/repo/ObservationRepoSpec.scala

Removes a couple of edit complications that aren't necessary anymore.

Small edit simplification

---

.github/workflows/scala.yml

CI, why not

---

docs/unshareTargets.md
modules/core/src/main/scala/lucuma/odb/api/model/ValidatedInput.scala

This PR presents for discussion some ideas about how to change the API to remove target sharing.  Feedback is particularly encouraged here.

No sharing targets

---

docs/ObserveApiProposal.md

This PR seeks feedback on, as of yet, work-in-progress ideas on enough of the Observe API to execute a single observation.

Observe API Notes

---

modules/core/src/main/scala/lucuma/odb/api/model/FocalPlane.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceMode.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/model/SpectroscopyCapabilities.scala
modules/core/src/main/scala/lucuma/odb/api/model/SpectroscopyRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ConstraintSetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/RefinedSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceRequirementsMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceRequirementsSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbObservationModel.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbScienceRequirements.scala
modules/core/src/test/scala/lucuma/odb/api/repo/ObservationRepoSpec.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

This is a first approximation at storing the science requirements params in the backend. I have some questions I want to ask inline but this is ready to be tested with the frontend

Add science requirements to observations

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationQuery.scala

Adds grouping by common science requirements.

Group by science requirements

---

docs/ScienceConfiguration.md
modules/core/src/main/scala/lucuma/odb/api/model/ConfigurationMode.scala
modules/core/src/main/scala/lucuma/odb/api/model/InstrumentConfigModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/MagnitudeModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceConfigurationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/model/SpectroscopyRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceConfigurationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceConfigurationSchema.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbObservationModel.scala
modules/core/src/test/scala/lucuma/odb/api/repo/ObservationRepoSpec.scala
modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

For details see `docs/ScienceConfiguration.md`
We way want to add an `editScienceConfiguration` operation as well

Support adding and editing the base configuration of an observation

---

modules/service/src/test/scala/OdbSuite.scala

A minor update to `OdbSuite` that allows the caller to specify which client(s) to use (http, ws, or both).  This capability isn't used here but will be used in another branch.

Allow queryTest caller to specify client(s)

---

modules/core/src/main/scala/lucuma/odb/api/model/ScienceConfigurationModel.scala

Signed-off-by: Carlos Quiroz <carlos.quiroz@noirlab.edu>

Fix assigning gmos south filter

---

modules/service/src/main/resources/logback.xml
modules/service/src/test/scala/OdbSuite.scala
modules/service/src/test/scala/ProgramTargetEditSubscriptionSuite.scala

After being stumped for a while because of a dumb mistake, here is a basic subscription test. The ergonomics may not be good in the long run but it's a start. I left in some debug logging because I suspect we'll need it.

add a subscription test

---

modules/core/src/main/scala/lucuma/odb/api/schema/TargetSchema.scala

Adds a `program` field to the `Target` and `TargetEnvironment` schema.  For example
```
query ScienceTarget {
scienceTarget(observationId: "o-2") {
name
program { name }
}
}
```
may produce
```
{
"data": {
"scienceTarget": {
"name": "NGC 5949",
"program": {
"name": "The real dark matter was the friends we made along the way"
}
}
}
}
```

Add program field to target and target environment

---

modules/service/src/main/scala/lucuma/odb/api/service/Init.scala

5s exposure

---

modules/core/src/main/scala/lucuma/odb/api/model/ObservationModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetEnvironmentModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/test/scala/lucuma/odb/api/repo/arb/ArbTables.scala
modules/service/src/test/scala/test/TestInit.scala
modules/service/src/test/scala/test/targets/TargetEnvironmentMutationSuite.scala

Checks that all targets assigned to an observation reference the same program.

Validate assigned target's program

---

modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetModel.scala
modules/core/src/main/scala/lucuma/odb/api/repo/TargetRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/RepoContext.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SubscriptionType.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetQuery.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetSchema.scala
modules/service/src/test/scala/test/targets/ScienceTargetMutationSuite.scala

Adds a `cloneTarget` mutation to create a target copy that is set to `PRESENT`

Clone target

---

modules/core/src/main/scala/lucuma/odb/api/schema/TargetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetQuery.scala

Since Andy mentioned he might be looking at it, I added a few crumbs of documentation.

A bit of target API documentation

---

modules/core/src/main/scala/lucuma/odb/api/schema/SourceProfileSchema.scala

Signed-off-by: Carlos Quiroz <carlos.quiroz@noirlab.edu>

Tiny leftover

---

modules/core/src/main/scala/lucuma/odb/api/model/targetModel/SourceProfileModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/SourceProfileSchema.scala
modules/core/src/main/scala/lucuma/odb/api/schema/TargetQuery.scala
modules/core/src/test/scala/lucuma/odb/api/model/arb/ArbSourceProfileModel.scala

Some source profile cleanup

---

modules/core/src/main/scala/lucuma/odb/api/model/ElevationRangeModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/SourceProfileModel.scala
modules/core/src/main/scala/lucuma/odb/api/model/targetModel/TargetEnvironmentModel.scala

I'd meant to include these in the original `liftState` PR (#507), but mistakenly left it out.  It's some minor cleanup and usage of `liftState` in a few more places.

liftState cleanup

---

modules/core/src/main/scala/lucuma/odb/api/schema/ConstraintSetMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceConfigurationMutation.scala

Fixes a few incorrectly named inputs.

fix input names

---

modules/core/src/main/scala/lucuma/odb/api/model/ScienceConfigurationModel.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceConfigurationMutation.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ScienceConfigurationSchema.scala

Adds the GMOS (North and South) FPUs to the science configuration as a required field.

Add GMOS FPU to science configuration

---

Procfile

Remove deprecated container memory management flags from Procfile

Remove java flags from Procfile

---

modules/core/src/main/scala/lucuma/itc/client/ItcSpectroscopyInput.scala
modules/service/src/main/scala/lucuma/odb/api/service/Config.scala

To be coordinated with the ITC update deployment.

ITC API Update

---

modules/core/src/main/scala/lucuma/odb/api/repo/ObservationRepo.scala
modules/core/src/main/scala/lucuma/odb/api/schema/ObservationMutation.scala
modules/service/src/test/scala/MutationSuite.scala
modules/service/src/test/scala/test/TestInit.scala

Adds a mutation to bulk edit the science mode.

bulkEditScienceMode

---

modules/core/src/main/scala/lucuma/gen/SequenceComputation.scala

Instead of an "internal server error" for ITC issues, we can display a slightly more informative message.
```
{
"data": {
"observation": {
"execution": {
"executionConfig": null
}
}
},
"errors": [
{
"message": "Could not extract required ITC query input from o-2",
"path": [
"observation",
"execution",
"executionConfig"
],
"locations": [
{
"line": 10,
"column": 7
}
]
}
]
}
```
I'm not sure whether this is the right thing to do -- it isn't like the user made some mistake that they can fix -- but it seems better than 500 internal server error?   The execution config result is optional, should we instead just silently return none?

somewhat better ITC query failure messages

---

modules/service/src/test/scala/test/ProgramMutationSuite.scala

These tests are not a complete test of all the possibilities in the API. More can be added if anyone thinks there should be.

Add some program mutation tests.

---

modules/core/src/main/scala/lucuma/odb/api/model/query/WhereStringInput.scala
modules/core/src/test/scala/lucuma/odb/api/model/query/WhereStringSuite.scala

Just some string matching test cases.

where string tests

---

modules/service/src/test/scala/test/targets/TargetMutationSuite.scala

A simple test that when editing multiple items a failure to any means nothing is changed, even if individually it would be successful for some items.

simple transaction test

---

modules/core/src/main/scala/lucuma/itc/client/ItcSpectroscopyInput.scala
modules/core/src/main/scala/lucuma/odb/api/model/ScienceMode.scala
modules/core/src/main/scala/lucuma/odb/api/model/SpectroscopyRequirements.scala
modules/core/src/main/scala/lucuma/odb/api/model/gmos/longslit/LongSlit.scala

Updates the ITC call to respect the "override" exposure time mode and wavelength options in the science mode.

Respect advanced in itc call
